#!/bin/bash
if [ $# -eq 0 ]
then
    echo "Usage: gh cancel-runs <owner>/<name>"
    exit 1
fi

# from: https://stackoverflow.com/a/60766849/5693170
# modified to be used as a gh extension to avoid specifying tokens

# Using tee to disable pager
ids=($(gh api repos/$1/actions/runs --jq \
            '.workflow_runs[] | select([.status] | inside(["in_progress", "queued"])) | .id' \
    | tee))

for id in $ids
do
    echo "Cancelling $id"
    gh api -X POST repos/$1/actions/runs/$id/cancel | tee
done
echo
